---
- hosts: 192.168.1.107
  become: yes
  tasks:
    - name: apache2
      apt: name=apache2 state=latest
- hosts: 192.168.1.108
  become: yes
  tasks:
    - name: apache
      yum: name=httpd state=latest
